// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMapData(arg1) {
  return window['go']['main']['App']['GetMapData'](arg1);
}

export function GetMapList(arg1) {
  return window['go']['main']['App']['GetMapList'](arg1);
}

export function SelectMapDirectory() {
  return window['go']['main']['App']['SelectMapDirectory']();
}
