// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function GetMapData(arg1:string):Promise<main.MapData>;

export function GetMapList(arg1:string):Promise<Array<string>>;

export function SelectMapDirectory(arg1:context.Context):Promise<string>;
